
ALTER SESSION SET CONTAINER = ORCLPDB1;

GRANT CONNECT TO jdbc CONTAINER=CURRENT;
GRANT CREATE SESSION TO jdbc CONTAINER=CURRENT;
GRANT RESOURCE TO jdbc CONTAINER=CURRENT;
GRANT SELECT_CATALOG_ROLE TO jdbc CONTAINER=CURRENT;

ALTER USER jdbc QUOTA 100M ON USERS;
